### ISSUE TITLE
Список задач без документации

### ISSUE THREAD

**Issue by Ukolnir** [Taally/FIIT_6_compiler#132]
- [x] Разработка шаблона документа на задачу #80 
- [ ] Сбор документации по всем задачам
- [ ] Интеграция документации в единый документ PDF
- [x] Разработка шаблона документа на задачу #80 
- [ ] Сбор документации по всем задачам
- [ ] Интеграция документации в единый документ PDF
- [x] Разработка шаблона документа на задачу #80 
- [ ] Сбор документации по всем задачам
- [ ] Интеграция документации в единый документ PDF
- [x] Разработка шаблона документа на задачу #80 
- [ ] Сбор документации по всем задачам
- [ ] Интеграция документации в единый документ PDF

**Comment by Molkree** [comment]
На `ReplaceExpr&Stat` видимо нужно мне писать док? Это залила @Taally, потом всякие правки вносили @Ukolnir, я, @NikMozd и @Taally. К вот этому [моменту](https://github.com/Taally/FIIT_6_compiler/blob/8a8d9f36ddaba4604c331a6c0119a92c0a31492e/Visitors/ChangeVisitor.cs) у нас там была обработка для всех видов нод, а потом вот тут https://github.com/Taally/FIIT_6_compiler/commit/67fe736137cd6645a9bbe8c06da4fcb0e861f0be я обобщил все эти случаи, введя списки дочерних выражений/операторов во всех нодах.

**Comment by Molkree** [comment]
По `FillParent` не уверен, по истории файла там только я, но это всё равно просто копипаста из лекций/исходного архива вроде бы, так что любой может написать.

**Comment by Ukolnir** [comment]
@Molkree, можно объединить эти два таска (даже три вместе с FillParent, просто написать про него где-то в практической части). Можешь указать соавторов. Думаю, отдать этот таск лучше тебе, так как изменений ты больше привнес и твоя версия осталась в проекте
