### ISSUE TITLE
Тесты на оптимизации по абстрактному синтаксическому дереву

### ISSUE THREAD

**Issue by NikMozd** [Taally/FIIT_6_compiler#134]
- [x] Умножение/деление на единицу `OptExprMultDivByOne` @Taally @Ukolnir #157
- [x] Умножение на ноль `OptExprMultZero` @aevseenko @Tessecrack #157
- [x] Свёртка констант `OptExprAlgebraic` @tefadivan ~~тут баг #145, придётся фиксить~~ #164
- [x] Суммирование с нулём `OptExprSumZero` @aevseenko @Tessecrack #157
- [x] Вычитание самого себя `OptExprSubEqualVar` @tefadivan #164
- [x] Неравенство констант `OptExprWithOperationsBetweenConsts`  @d-enk #187 
- [x] Равенство констант ~~и переменных~~ `OptExprEqualBoolNumId` @ushakov-igor @xittz ~~сравнивать переменные тут не нужно, это другой таск (моей команды)~~ #167 
- [x] Равенство переменных `OptExprEqualToItself` @Molkree @NikMozd ~~мб дать имя, указывающее, что это только для переменных~~ #180
- [x] Неравенство переменных `OptExprSimilarNotEqual` @Ex1sTs @Sirozu нет никакого смысла перед заменой обрабатывать левое и правое поддерево, там просто переменные.

---

- [x] Присваивание самому себе `OptAssignEquality` @TheTapog @VadimKaryakin #177 
- [x] Замена ветвления с true в условии `OptStatIfTrue` @Taally @Ukolnir @Molkree @NikMozd #163
- [x] Замена ветвления с false в условии `OptStatIfFalse` @Ex1sTs @Sirozu @d-enk 
- [x] Замена ветвления с пустыми ветками `IfNullElseNull` @TheTapog @VadimKaryakin #177 
- [x] Удаление цикла while `OptWhileFalseVisitor` @xittz @ushakov-igor #167

---

- [x] Тесты на `ASTOptimizer`. Комбинация одиночных тестов, схоже с комбинированными тестами TAC #178

**Comment by patceev** [comment]
Удаление цикла while и Равенство констант/переменных OptExprEqualBoolNumId выполнено, пр-ы висят

**Comment by Ukolnir** [comment]
Слито

**Comment by Ex1sTs** [comment]
#183 содержит неравенство переменных OptExprSimilarNotEqual и замену ветвления с false в условии OptStatIfFalse
